# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-project-definition:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@4
        with:
            python-version: '3.11'

      - name: Install Python packages
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
      - name: Execute python validation script
        run: python validate_yaml.py